config/routes.rb
Rails.application.routes.draw do
  get 'document_preview/index'
  resources :paragraphs
  resources :messages
  get 'home/index'
  resources :documents
  resources :images
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :documents do
        get :get_all, on: :collection
        post :login, on: :collection
      end

      resources :images do
        get :get_all, on: :collection
      end

      resources :messages do
        get :get_all, on: :collection
        post :set_message, on: :collection
      end
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @messages = Message.all
    render json: @messages
  end

  def get_all
    @messages = Message.all
    render json: @messages
  end

  def show
    @messages = Message.find(params[:id])
    render json: @message
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      render json: {msg: ' The message is successfully uploaded'}
    else
      render json: {user: @message.errors},status:unprocessable_entity
    end
  end

  def set_message
    @message = Message.new(message_params)
    if @message.save
      render json: {msg: ' The message is successfully uploaded'}
    else
      render json: {user: @message.errors},status:unprocessable_entity
    end
  end

  def message_params
    params.permit(:name, :surname, :email, :title, :text)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:name, :surname, :email, :title, :text)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :surname %>
    <%= f.input :email %>
    <%= f.input :title %>
    <%= f.input :text %>
  </div>

  <div class="form-actions">  
    <%= f.button :submit, value: "#{f.object.new_record? ? 'Confirmar datos' : 'Actualizar'}", class: "btn-primary" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3>message</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Ver', @message %>
        <%= link_to ' | Atras',messages_path %>
      </div>
    </div>
  </div>
</div>
<br />

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
      <h4>Mensajes recibidos</h4>
    </div>
    <!-- <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Crear message', new_message_path, class: 'btn btn-primary' %>
      </div>
    </div> -->
  </div>
</div>
<br />
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Email</th>
        <th>Asunto</th>
        <th>Texto del mensaje</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @messages.each do |message| %>
      <tr>
        <td><%= message.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
        <td><%= message.name %></td>
        <td><%= message.surname %></td>
        <td><%= message.email %></td>
        <td><%= message.title %></td>
        <td><%= message.text %></td>        
        <td><div align="center"><%= link_to image_tag('delete-icon.png', :size => "20x20"), message, method: :delete, data: { confirm: 'Confirma el borrado del mensaje?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/messages/new.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3>message</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Atras',messages_path %>
      </div>
    </div>
  </div>
</div>
<br />
<%= render 'form' %>

app/views/messages/show.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3>message</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Editar', edit_message_path(@message) %>
        <%= link_to ' | Atras',messages_path %>
      </div>
    </div>
  </div>
</div>
<br />
<p><strong>Name:</strong><%= @message.name %></p>
<p><strong>Surname:</strong><%= @message.surname %></p>
<p><strong>Email:</strong><%= @message.email %></p>
<p><strong>Title:</strong><%= @message.title %></p>
<p><strong>Text:</strong><%= @message.text %></p>