config/routes.rb
Rails.application.routes.draw do
  get 'document_preview/index'
  resources :paragraphs
  resources :messages
  get 'home/index'
  resources :documents
  resources :images
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :documents do
        get :get_all, on: :collection
        post :login, on: :collection
      end

      resources :images do
        get :get_all, on: :collection
      end

      resources :messages do
        get :get_all, on: :collection
        post :set_message, on: :collection
      end
    end
  end

end

app/models/document.rb
class Document < ApplicationRecord
  has_many :paragraphs, dependent: :destroy
end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @documents = Document.all
    # render 'documents/index.json.jbuilder'
  end

  def get_all
    # http://localhost:3000/api/v1/documents/get_all
    @documents = Document.all
    render 'documents/get_all.json.jbuilder'
  end

  def show
    @document = Document.find(params[:id])
    render json: @document
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      render json: {msg: ' The document is successfully uploaded'}
    else
      render json: {user: @document.errors},status:unprocessable_entity
    end
  end

  def login
    pass = params[:password].to_s

    puts('---------------------------------------')
    puts(pass)


    if pass == '1234'
      render json: {auth: 'ok'}
    else
      render json: {auth: 'no ok'}
    end
  end

  def document_params
    params.permit(:title)
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /documents or /documents.json
  def index
    @documents = Document.all    
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :text)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for(@document) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.label 'Titulo' %>
    <%= f.input :title, label: false %>

    <%= f.label 'Texto' %>
    <%= f.input :text, label: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "#{f.object.new_record? ? 'Confirmar datos' : 'Actualizar'}", class: "btn-primary" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3>Edicion de Documento</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Ver', @document %>
        <%= link_to ' | Atras',documents_path %>
      </div>
    </div>
  </div>
</div>
<br />

<%= render 'form' %>

app/views/documents/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
      <h4>Documentos</h4>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Crear nuevo Documento', new_document_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<br />
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Titulo</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><div align="center"><%= link_to image_tag('examine-icon.png', :size => "20x20"), document %></td>
        <td><div align="center"><%= link_to image_tag('delete-icon.png', :size => "20x20"), document, method: :delete, data: { confirm: 'Confirma el borrado del documento?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/documents/new.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3>Ingreso de Documento</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Atras',documents_path %>
      </div>
    </div>
  </div>
</div>
<br />
<%= render 'form' %>

app/views/documents/show.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3><%= @document.title %></h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Editar titulo', edit_document_path %>
        <%= link_to ' | Vista Previa',document_preview_index_url(:id => @document) %>
        <%= link_to ' | Atras',documents_path %>
      </div>
    </div>
  </div>
</div>
<br />

<div align="right">
  <%= link_to 'Agregar parrafo', new_paragraph_path(:document_id => @document.id), class: 'btn btn-primary' %>
</div>

<br>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Texto</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @document.paragraphs.each do |paragraph| %>
      <tr>
        <td><%= paragraph.title %></td>
        <td><%= paragraph.text %></td>
        <td><div align="center"><%= link_to image_tag('examine-icon.png', :size => "20x20"), paragraph %></td>
        <td><div align="center"><%= link_to image_tag('delete-icon.png', :size => "20x20"), paragraph, method: :delete, data: { confirm: 'Confirma el borrado del parrafo?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>