config/routes.rb
Rails.application.routes.draw do
  get 'document_preview/index'
  resources :paragraphs
  resources :messages
  get 'home/index'
  resources :documents
  resources :images
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :documents do
        get :get_all, on: :collection
        post :login, on: :collection
      end

      resources :images do
        get :get_all, on: :collection
      end

      resources :messages do
        get :get_all, on: :collection
        post :set_message, on: :collection
      end
    end
  end

end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  belongs_to :document
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :set_paragraph, only: %i[ show edit update destroy ]

  # GET /paragraphs or /paragraphs.json
  def index
    @paragraphs = Paragraph.all
  end

  # GET /paragraphs/1 or /paragraphs/1.json
  def show
  end

  # GET /paragraphs/new
  def new
    @paragraph = Paragraph.new
    @paragraph.document_id= params[:document_id]
  end

  # GET /paragraphs/1/edit
  def edit
  end

  # POST /paragraphs or /paragraphs.json
  def create
    @paragraph = Paragraph.new(paragraph_params)

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph.document, notice: "Paragraph was successfully created." }
        format.json { render :show, status: :created, location: @paragraph }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragraphs/1 or /paragraphs/1.json
  def update
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to @paragraph.document, notice: "Paragraph was successfully updated." }
        format.json { render :show, status: :ok, location: @paragraph }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1 or /paragraphs/1.json
  def destroy
    @documento = @paragraph.document

    @paragraph.destroy
    respond_to do |format|
      format.html { redirect_to @documento, notice: "Paragraph was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paragraph_params
      params.require(:paragraph).permit(:title, :text, :document_id)
    end
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/views/paragraphs/_form.html.erb
<%= simple_form_for(@paragraph) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, :label => 'Titulo' %>
    <%= f.input :text, :label => 'Texto' %>
    <%= f.input :document_id, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "#{f.object.new_record? ? 'Confirmar datos' : 'Actualizar'}", class: "btn-primary" %>
  </div>
<% end %>

app/views/paragraphs/edit.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3>Edicion de parrafo</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Atras', @paragraph %>      
      </div>
    </div>
  </div>
</div>
<br />

<%= render 'form' %>

app/views/paragraphs/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
      <h3>Parrafos</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Agregar parrafo', new_paragraph_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<br />
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Texto</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @paragraphs.each do |paragraph| %>
      <tr>
        <td><%= paragraph.title %></td>
        <td><%= paragraph.text %></td>
        <td><%= link_to 'Ver', paragraph %></td>
        <td><%= link_to 'Editar', edit_paragraph_path(paragraph) %></td>
        <td><%= link_to 'Borrar', paragraph, method: :delete, data: { confirm: 'Confirma el borrado del parrafo?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/paragraphs/new.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3>Nuevo parrafo</h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Atras',paragraphs_path %>
      </div>
    </div>
  </div>
</div>
<br />
<%= render 'form' %>

app/views/paragraphs/show.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <div class="row">
    <div class="col-sm-6">
        <h3><%= @paragraph.title %></h3>
    </div>
    <div class="col-sm-6">
      <div align="right">
        <%= link_to 'Editar', edit_paragraph_path(@paragraph) %>
        <%= link_to ' | Atras',@paragraph.document %>
      </div>
    </div>
  </div>
</div>

<br />

<p><%= @paragraph.text %></p>