config/routes.rb
Rails.application.routes.draw do
  get 'document_preview/index'
  resources :paragraphs
  resources :messages
  get 'home/index'
  resources :documents
  resources :images
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :documents do
        get :get_all, on: :collection
        post :login, on: :collection
      end

      resources :images do
        get :get_all, on: :collection
      end

      resources :messages do
        get :get_all, on: :collection
        post :set_message, on: :collection
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bsmanager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #71da71;">
      <a class="navbar-brand ml-5" href="#">BSManager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Imagenes", images_path, class: "nav-item nav-link" %>
          <%= link_to "Documentos", documents_path, class: "nav-item nav-link" %>
          <%= link_to "Mensajes", messages_path, class: "nav-item nav-link" %>
        </div>
      </div>
    </nav>



    <div class='container'>
      <%= yield %>
    </div>
  </body>

</html>